<a href="https://colab.research.google.com/github/Najpraphatsarang/cos3302/blob/main/cos3302week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Example:

#1.Hello world

In [ ]:
# Never mind this statement, for compatibility resons from__future__ import absolute_import, division, print_function, unicode_literais
print("Hello World")

Hello World


#2.Function, Conditionals, and Iteration

In [ ]:
def HelloWorldXY(x, y):
  if (x < 10):
    print("Hello World, x was < 10")
  elif (x < 20):
    print("Hello World, x was >= 10 but < 20")
  else:
    print("Hello World, x was >= 20")
  return x + y

for i in range(8, 25, 5):  # i=8, 13, 18, 23 (start, stop, step)
  print("--- Now running with i: {}".format(i))
  r = HelloWorldXY(i,i)
  print("Result from HelloWorld: {}".format(r))

--- Now running with i: 8
Hello World, x was < 10
Result from HelloWorld: 16
--- Now running with i: 13
Hello World, x was >= 10 but < 20
Result from HelloWorld: 26
--- Now running with i: 18
Hello World, x was >= 10 but < 20
Result from HelloWorld: 36
--- Now running with i: 23
Hello World, x was >= 20
Result from HelloWorld: 46


In [ ]:
print(HelloWorldXY(1,2))

Hello World, x was < 10
3


#3.Various kinds of loops starting at 0 to 2

In [ ]:
print("Iterate over the items. `range(2)` is like a list [0,1].")
for i in range(2):
  print(i)
  print("Iterate over an actual list.")
for i in [0,1]:
  print(i)
  print("While works")
  
i = 0
while i < 2:
  print(i)
  i += 1

Iterate over the items. `range(2)` is like a list [0,1].
0
Iterate over an actual list.
1
Iterate over an actual list.
0
While works
1
While works
0
1


#4.Numpy and lists
Numpy as np is the fundamental package for scientific computing with Python.


Lists (Array) are data structure in Python that is a mutable, or changeable, ordered sequence of elements. Each
element or value that is inside of a list is called an item. Just as strings are defined as characters between quotes,
lists are defined by having values between square brackets [ ].

In [ ]:
sea_creatures = ['shark', 'cuttlefish', 'squid', 'mantis shrimp', 'anemone']

In [ ]:
sea_creatures[0] = 'shark'
sea_creatures[2] = 'squid'
sea_creatures[4] = 'anemone'

In [ ]:
import numpy as np 
# Make numpy available using np.
# Create a numpy array, and append an element
a = np.array(["Hello", "World"])
a = np.append(a, "!")
print("Current array: {}".format(a))
print("Printing each element")
for i in a:
  print(i)
  print("\nPrinting each element and their index")
for i,e in enumerate(a):
  print("Index: {}, was: {}".format(i, e))

Current array: ['Hello' 'World' '!']
Printing each element
Hello

Printing each element and their index
World

Printing each element and their index
!

Printing each element and their index
Index: 0, was: Hello
Index: 1, was: World
Index: 2, was: !


In [ ]:
print("\nShowing some basic math on arrays")
b = np.array([0,1,4,3,2])
print("Max: {}".format(np.max(b)))
print("Average: {}".format(np.average(b)))
print("Max index: {}".format(np.argmax(b)))


Showing some basic math on arrays
Max: 4
Average: 2.0
Max index: 2


In [ ]:
print("\nYou can print the type of anything")
print("Type of b: {}, type of b[0]: {}".format(type(b), type(b[0])))


You can print the type of anything
Type of b: <class 'numpy.ndarray'>, type of b[0]: <class 'numpy.int64'>


In [ ]:
print("\nUse numpy to create a [3,3] dimension array with random number")
c = np.random.rand(3, 3)
print(c)


Use numpy to create a [3,3] dimension array with random number
[[0.4986432  0.30683947 0.10701167]
 [0.8605908  0.05245787 0.44321714]
 [0.27077221 0.74012761 0.58371847]]


In [ ]:
print("\nShowing some basic math on arrays")
b = np.array([0,1,4,3,2])
print("Max: {}".format(np.max(b)))
print("Average: {}".format(np.average(b)))
print("Max index: {}".format(np.argmax(b)))


Showing some basic math on arrays
Max: 4
Average: 2.0
Max index: 2


In [ ]:
print("\nYou can print the dimensions of arrays")
print("Shape of a: {}".format(a.shape))
print("Shape of b: {}".format(b.shape))
print("Shape of c: {}".format(c.shape))


You can print the dimensions of arrays
Shape of a: (3,)
Shape of b: (5,)
Shape of c: (3, 3)


##Exercise

#1.Colab: Create a code cell underneath this text cell and add code to:
- List the path of the current directory (pwd)
- Go to / (cd) and list the content (ls-l)

In [ ]:
!pwd
!cd /
!ls -l
print("Hello")

/content
total 4
drwxr-xr-x 1 root root 4096 Jul 13 13:43 sample_data
Hello


#2.Python lists without Numpy: Print the second item in the fruits list:

In [ ]:
fruits = ["apple", "banana", "cherry"]
print(fruits[1])

banana


#3.Change the value from “apple” to “kiwi”, in the fruits list:

In [ ]:
fruits[0] = "kiwi"
for x in fruits:
  print(x)

kiwi
banana
cherry


#4.Use the append method to add “orange” to the fruits list:

In [ ]:
fruits.append("orange")
for x in fruits:
  print(x)

kiwi
banana
cherry
orange


#5.Use the insert method to add “lemon” as the second item in the fruits list:

In [ ]:
fruits.insert(1,"lemon")
for x in fruits:
  print(x)

kiwi
lemon
banana
cherry
orange


#6.Use the remove method to delete “banana” from the fruits list:

In [ ]:
fruits.remove("banana")
for x in fruits:
  print(x)

kiwi
lemon
cherry
orange


#7.Python If...Else: Print “Hello World” if a is greater than b:

In [ ]:
a = 50
b = 10 
c = 20
d = 20
if a>b:
  print("Hello World")

Hello World


#8. Print “Hello World” if a is not equal to b:

In [ ]:
if a!=b:
  print("Hello World")

Hello World


#9. Print “Yes” if a is equal to b, otherwise print “No”:

In [ ]:
if a == b:
  print("Yes")
else:
  print("No")

No


#10. Print “1” if a is equal to b, print “2” if a is greater than b, otherwise print “3”:

In [ ]:
if a == b:
  print("1")
elif a > b:
  print("2")
else:
  print("3")

2


#11. Print “Hello” if a is equal to b, and c is equal to d:

In [ ]:
if a == b and c == d:
  print("Hello")

#12. Print “Hello” if either a is equal to b, or c is equal to d:

In [ ]:
if a == b or c == d:
  print("Hello")

Hello


#13. Python Loops: Print i as long as i is less than 6:

In [ ]:
i = 1
while i<6:
  print(i)
  i += 1

1
2
3
4
5


#14. From #13 stop the loop if i is 3:

In [ ]:
i = 1
while i<6:
  print(i)
  if i == 3:
    break
  i += 1

1
2
3
